# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/analyser.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/analyser.proto\".\n\nAudioFrame\x12\r\n\x05index\x18\x01 \x01(\r\x12\x11\n\tamplitude\x18\x02 \x01(\x11\x62\x06proto3')



_AUDIOFRAME = DESCRIPTOR.message_types_by_name['AudioFrame']
AudioFrame = _reflection.GeneratedProtocolMessageType('AudioFrame', (_message.Message,), {
  'DESCRIPTOR' : _AUDIOFRAME,
  '__module__' : 'proto.analyser_pb2'
  # @@protoc_insertion_point(class_scope:AudioFrame)
  })
_sym_db.RegisterMessage(AudioFrame)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOFRAME._serialized_start=24
  _AUDIOFRAME._serialized_end=70
# @@protoc_insertion_point(module_scope)
